youta/config/routes.rb
Rails.application.routes.draw do
  root 'lessons#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :lessons do
    resources :questions
    resources :students, only: [:index, :create, :destroy]
    resources :tags, only:[:index, :create, :destroy]
  end
  resources :comments, only: [:create, :edit, :update]

  resources :users, only: [:show, :edit, :update]
  get 'management' => 'users#manage'

end

youta/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  validates :user_id, presence: true
  validates :question_id, presence: true
  validates :content, presence: true
end

youta/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :subscribing
  before_action :author_check, only: [:edit, :update]

  def create
    question = Question.find(params[:comment][:question_id])
    comment = Comment.new(comment_params)
    unless comment.save
      flash[:warning] = "コメントに何も入力されていません"
    end
    redirect_to lesson_question_path(question.lesson, question)
  end

  def edit
    @comment = Comment.find(params[:id])
    @question = @comment.question
    @lesson = @question.lesson
  end

  def update
    @comment = Comment.find(params[:id])
    @question = @comment.question
    @lesson = @question.lesson

    @comment.content = params[:comment][:content]
    if @comment.save
      flash[:success] = "コメントを更新しました"
      redirect_to lesson_question_path(@lesson, @question)
    else
      flash[:warning] = "コメントを更新できませんでした"
      render 'edit'
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :user_id, :question_id)
    end

    #before_action
    def subscribing
      question = Question.find(params[:comment][:question_id]) if params[:comment].present?
      question ||= Comment.find(params[:id]).question

      unless logged_in? && teacher_or_student_of(question.lesson)
        redirect_to root_path, notice: '受講していない授業にコメントできません'
      end
    end

    def teacher_or_student_of(lesson)
      current_user.lessons.include?(lesson) || current_user.lectures.include?(lesson)
    end

    def author_check
      comment = Comment.find(params[:id])
      question = comment.question
      unless logged_in? && comment.user == current_user
        redirect_to lesson_question_path(question.lesson, question)
      end
    end

end

youta/app/views/comments/_comment.html.haml
- bubble_class = ["chat-bubble"]
- bubble_class << "me" if current_user == comment.user
.chat-area
  %div{ id: "comment-#{comment.id}", class: "comment-info" }
    = comment.user.name
    - if current_user == comment.user
      = link_to '編集する', edit_comment_path(comment, anchor: "comment-#{comment.id}"), class: "comment-edit-link"
  %div{ class: bubble_class }= comment.content.gsub("\n", "<br />").html_safe

youta/app/views/comments/_comment_edit.html.haml
.chat-area
  %div{ id: "comment-#{comment.id}", class: "comment-info" }
    = comment.user.name
    - if current_user == comment.user
      = link_to '編集をやめる',
            lesson_question_path(comment.question.lesson, comment.question), class: "comment-edit-link"
  .chat-bubble.me.edit
    = form_tag comment_path(comment), method: :put do
      = hidden_field_tag 'comment[question_id]', comment.question.id
      = text_area_tag 'comment[content]', comment.content.gsub("\n", "<br />").html_safe
      .pull-right= submit_tag '更新', class: "btn btn-success"

youta/app/views/comments/_comment_form.html.haml
-# locals
-# question : to post comment on
.col-xs-10.col-xs-offset-1.comment-form
  = form_for(Comment.new) do |f|
    = f.hidden_field :question_id, value: question.id
    = f.hidden_field :user_id, value: current_user.id
    = f.text_area :content, placeholder: "気軽にコメントしてみましょう．"
    .pull-right= f.submit 'コメント', class: 'btn btn-success'

  = form_for([@question.lesson, @question]) do |f|
    = f.hidden_field "solved", value: !@question.solved
    - text = @question.solved ? "未解決に戻す" : "解決済みにする"
    .pull-right.space-right= f.submit text, class: 'btn btn-default'

youta/app/views/comments/_comment_official.html.haml
.chat-area.comment-info
  %span= "#{comment.user.name} さんがこの質問を"
  - if comment.content == "close"
    = render partial: 'questions/solved_tag', locals: { solved: true, size: 'xs' }
    としました
  - elsif comment.content == "open"
    = render partial: 'questions/solved_tag', locals: { solved: false, size: 'xs' }
    に戻しました

youta/app/views/comments/edit.html.haml
.back-link
  = link_to "＜ #{@lesson.title} の質問一覧に戻る", lesson_questions_path(@lesson)
.container
  = render partial: 'questions/question_info', locals: { question: @question }
  %hr
  .chat-box
    - @question.comments.each do |comment|
      - if comment.official?
        = render partial: 'comment_official', locals: { comment: comment }
      - elsif comment == @comment
        = render partial: 'comment_edit', locals: { comment: comment }
      - else
        = render partial: 'comment', locals: { comment: comment }
    - if have_right_to_comment(@lesson, current_user)
      %hr
      = render partial: 'comments/comment_form', locals: { question: @question }