youta/config/routes.rb
Rails.application.routes.draw do
  root 'lessons#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :lessons do
    resources :questions
    resources :students, only: [:index, :create, :destroy]
    resources :tags, only:[:index, :create, :destroy]
  end
  resources :comments, only: [:create, :edit, :update]

  resources :users, only: [:show, :edit, :update]
  get 'management' => 'users#manage'

end

youta/app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many :editor_relationships, dependent: :destroy
  has_many :editors, through: :editor_relationships, source: :user
  has_many :subscriptions, dependent: :destroy
  has_many :students, through: :subscriptions, source: :user
  has_many :questions
  has_many :tags
  validates :title, presence: true
  validates :period, numericality: { greater_than: 0 }
  validates_inclusion_of :day_of_week, in: 0..6


  def self.day_of_week_to_str(day_of_week)
    DAY_OF_WEEK_MAP[day_of_week]
  end

  def self.period_to_str(period)
    period.to_s + '限' unless period == 0
  end

  def tags_to_str
    tags.map { |tag| tag.name }.join(',')
  end

  private
    DAY_OF_WEEK_MAP = ['月曜','火曜','水曜','木曜','金曜']

end

youta/app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :signed_in_user
  before_action :admin_user, except: :index

  def index
    @lessons = Lesson.all
  end
  def new
    @lesson = Lesson.new
  end
  def create
    @lesson = Lesson.new(user_params)
    if @lesson.save
      flash[:success] = "授業「#{@lesson.title}」を作成しました"
      EditorRelationship.create(lesson_id: @lesson.id, user_id: current_user.id)
      redirect_to lessons_path
    else
      flash[:danger] = "授業の作成に失敗しました"
      render 'new'
    end
  end
  def edit
    @lesson = Lesson.find(params[:id])
  end
  def update
    @lesson = Lesson.find(params[:id])
    if @lesson.update_attributes(user_params)
      flash[:success] = "変更を保存しました"
      render 'edit'
    else
      flash[:danger] = "変更を保存できませんでした"
      render 'edit'
    end
  end
  def destroy
    Lesson.find(params[:id]).destroy
    redirect_to lessons_path
  end

  private

    def user_params
      params.require(:lesson).permit(:day_of_week, :period, :title)
    end
end

youta/app/helpers/lessons_helper.rb
module LessonsHelper
end

youta/app/views/lessons/_form.html.haml
-# locals
-# lesson : to dosplay
-# submit-msg : text on submit button
%div
  = form_for(lesson) do |f|
    %fieldset.form-group.col-xs-4
      = f.label :day_of_week, "曜日"
      = f.select :day_of_week, [['月曜',0],['火曜',1],['水曜',2],['木曜',3],['金曜',4]]

    %fieldset.form-group.col-xs-4
      = f.label :period, "時間"
      = f.select :period, [['1限',1],['2限',2],['3限',3],['4限',4],['5限',5],['6限',6]]

    .col-xs-4

    %fieldset.form-group.col-xs-12
      = f.label :title, "授業名"
      = f.text_field :title

    - unless lesson.new_record?
      %fieldset.form-group.col-xs-12
        = f.label :students_csv, "受講者(#{lesson.students.size}人)"
        = link_to '編集する', lesson_students_path(lesson)

      %fieldset.form-group.col-xs-12
        = f.label :tags, "授業内容(タグ)"
        = link_to '編集する', lesson_tags_path(lesson)
        %div
          = render partial: 'tags/button_like_tag', collection: lesson.tags


    %fieldset.form-group.col-xs-4.col-xs-offset-4.center
      = f.submit submit_msg, class: "btn btn-success"

youta/app/views/lessons/_lesson.html.haml
-# local variable
-# item_link : method object which returns item link with lesson object as argument
-# css : array of css class to apply on li
- li_class = "lesson-row"
- li_class << '-' << css if defined?(css) # ex. lesson-row-tab

%li{ id: "lesson-#{lesson.id}", class: li_class }
  %div
    .lesson-schedule
      %span= Lesson.day_of_week_to_str lesson.day_of_week
      %span= Lesson.period_to_str lesson.period
    = link_to lesson.title, item_link.call(lesson)

youta/app/views/lessons/edit.html.haml
.page-top-info
  %span.h3= "#{@lesson.title} を編集する"
=render partial: 'form', locals: { lesson: @lesson, submit_msg: "更新する" }

youta/app/views/lessons/index.html.haml
%div.page-top-info
  %h3 授業一覧
%ul{ class: "list-group" }
  = render(partial: @lessons, locals: { item_link: method(:lesson_questions_path) }) || '授業は登録されていません.'

youta/app/views/lessons/new.html.haml
%h1 授業を作成する
= render partial: 'form', locals: { lesson: @lesson, submit_msg: "作成する" }