youta/config/routes.rb
Rails.application.routes.draw do
  root 'lessons#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :lessons do
    resources :questions
    resources :students, only: [:index, :create, :destroy]
    resources :tags, only:[:index, :create, :destroy]
  end
  resources :comments, only: [:create, :edit, :update]

  resources :users, only: [:show, :edit, :update]
  get 'management' => 'users#manage'

end

youta/app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-default
  %div.container
    = link_to 'Youta', root_path, id: 'logo'
    .navbar-header
      %button.navbar-toggle(data-toggle="collapse" data-target="#gnavi")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    #gnavi.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if logged_in?
          %li= link_to "マイページ", user_path(current_user)
          %li= link_to "ログアウト", logout_path, method: :delete
          - if current_user.admin?
            %li= link_to '管理画面', management_path

youta/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Youta
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    - flash.each do |key, value|
      %div{ class: ["alert","alert-#{key}"] }
        = value
    %div.container= yield