youta/config/routes.rb
Rails.application.routes.draw do
  root 'lessons#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :lessons do
    resources :questions
    resources :students, only: [:index, :create, :destroy]
    resources :tags, only:[:index, :create, :destroy]
  end
  resources :comments, only: [:create, :edit, :update]

  resources :users, only: [:show, :edit, :update]
  get 'management' => 'users#manage'

end

youta/app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.student_id = student_id.downcase }
  has_many :comments
  has_many :questions
  has_many :editor_relationships, dependent: :destroy
  has_many :lectures, through: :editor_relationships, source: :lesson
  has_many :subscriptions, dependent: :destroy
  has_many :lessons, through: :subscriptions
  has_many :good_relationships
  has_many :good_questions, through: :good_relationships, source: :question
  validates :name, presence: true
  validates :student_id, length: { is: 8 },
    format: { with: /\A[ABab][0-9]{7}/ },
    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password,
    presence: true,
    length: { minimum: 6 },
    on: :create
  validates :password,
    length: { minimum: 6 },
    allow_blank: true,
    on: :update

  def comment(question, content)
    comments.create(question_id: question.id, content: content)
  end

  def post_good(question)
    good_relationships.create(question_id: question.id)
  end

  def cancel_good(question)
    good_relationships.find(question.id).destroy
  end

end

youta/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user, except: :manage
  before_action :admin_user, only: :manage

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "登録情報を更新しました"
      redirect_to user_path(@user)
    else
      flash[:warning] = "登録情報を更新できませんでした"
      render 'edit'
    end
  end

  def manage
    @user = current_user
  end

  private
    def user_params
      params.require(:user).permit(:student_id, :name, :password, :password_confirmation)
    end

    # before_action
    def correct_user
      @user = User.find(params[:id])
      unless logged_in? && current_user == @user
        redirect_to root_path, notice: "不正なアクセスです"
      end
    end
end

youta/app/helpers/users_helper.rb
module UsersHelper
end

youta/app/views/users/edit.html.haml
%div.page-top-info
  %h3 プロフィールの編集

%div
  = form_for(@user) do |f|
    = f.hidden_field :student_id, value: @user.student_id

    %fieldset.form-group
      = f.label :name, '名前'
      = f.text_field :name
    %fieldset.form-group
      = f.label :password, 'パスワード'
      = f.password_field :password
      %small.text-muted 変更しない場合は空欄のまま「更新」をクリックしてください
    %fieldset.form-group
      = f.label :password_confirmation, 'パスワードの確認'
      = f.password_field :password_confirmation
    %fieldset.form-group.col-xs-4.col-xs-offset-4.center
      = f.submit '更新', class: "btn btn-success"

youta/app/views/users/manage.html.haml
%h1 管理画面
= link_to '授業を追加', new_lesson_path, class: "btn btn-success"

%ul.nav.nav-tabs.lesson-list
  %li.active
    %a あなたが作成した授業
%ul{ class: "list-group" }
  = render(partial: @user.lectures, locals: { item_link: method(:edit_lesson_path) })

youta/app/views/users/show.html.haml
%div.page-top-info
  %span.h3= "#{@user.name} さんのマイページ"
  = link_to 'プロフィールを編集する', edit_user_path(@user), class: "btn btn-link"
%ul.nav.nav-tabs
  %li.active
    %a 受講中の授業
= render(partial: @user.lessons, locals: { item_link: method(:lesson_questions_path), css: "tab" })